version: '3.5'

volumes:
    myguestbook_db:

networks:
    myguestbook_network:
        driver: bridge

services:
    database:
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports:
            - 5432:5432
        volumes:
            - myguestbook_db:/var/lib/postgresql/data
        networks:
            - myguestbook_network

    redis:
        image: redis:5-alpine
        ports:
            - 6379:6379
        networks:
            - myguestbook_network
